version: '3.8'

services:
  bot:
    image: rtimonin569/rst_bot:${IMAGE_TAG:-latest}
    container_name: rst_bot_container
    restart: unless-stopped
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TARGET_CHAT_ID: ${TARGET_CHAT_ID}
      FROM_EMAIL: ${FROM_EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EXCEL_PATH: /data/phonebook.xlsx
      PYTHONUNBUFFERED: '1'
    volumes:
      - rst_bot_data:/data
    networks:
      - bot_network

volumes:
  rst_bot_data:
    external: true
    name: rst_bot_data

networks:
  bot_network:
    driver: bridge
